name: Security Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build_app:
    name: Build Flask App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t sast ./app

  sonar_scan:
    name: SAST with SonarQube
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - uses: actions/checkout@v3
      - name: Run SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=my-vuln-app
            -Dsonar.organization=MON_ORGANISATION
            -Dsonar.sources=app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dast_zap:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP ZAP baseline scan
        run: |
          docker run --rm -v ${{ github.workspace }}/reports:/zap/reports \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:5000 \
            -r /zap/reports/zap_report.html

  dep_audit:
    name: Dependency Audit (pip-audit)
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - uses: actions/checkout@v3
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit -r app/requirements.txt --format=json > pip_audit.json
      - name: Upload audit results
        uses: actions/upload-artifact@v3
        with:
          name: pip-audit-report
          path: pip_audit.json
